services:
  - type: web
    name: tiktok-affiliate-bot
    env: node
    plan: free
    buildCommand: npm install && npx vite build --config vite.config.prod.js && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: tiktok-affiliate-bot
          property: port
      - key: TIKTOK_REDIRECT_URI
        value: https://dgtok-4u.onrender.com/api/tiktok/callback
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: TIKTOK_ADVERTISER_ID
        sync: false
      - key: TIKTOK_ACCESS_token
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tiktok-affiliate-db
          property: connectionString
      - key: WEBHOOK_SECRET
        generateValue: true

databases:
  - name: tiktok-affiliate-db
    databaseName: tiktok_affiliate
    user: tiktok_user
    plan: free